// <auto-generated />
using System;
using EF_Core.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EF_Core.Migrations
{
    [DbContext(typeof(TiemChungContext))]
    [Migration("20240920083239_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-rc.1.24451.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EF_Core.Model.CONGDAN", b =>
                {
                    b.Property<string>("MaCD")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CMND")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaCD");

                    b.ToTable("CONGDANs");

                    b.HasData(
                        new
                        {
                            MaCD = "CD001",
                            CMND = "123456789",
                            DiaChi = "Hà Nội",
                            Email = "",
                            HoTen = "Nguyễn Văn A",
                            NgaySinh = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0987654321"
                        });
                });

            modelBuilder.Entity("EF_Core.Model.LIEUVACXIN", b =>
                {
                    b.Property<string>("MaLieuVX")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaLoaiVX")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayHetHan")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgaySanXuat")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoLo")
                        .HasColumnType("int");

                    b.HasKey("MaLieuVX");

                    b.HasIndex("MaLoaiVX");

                    b.ToTable("LIEUVACXINs");

                    b.HasData(
                        new
                        {
                            MaLieuVX = "VX001-001",
                            MaLoaiVX = "VX001",
                            NgayHetHan = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgaySanXuat = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoLo = 1
                        },
                        new
                        {
                            MaLieuVX = "VX002-001",
                            MaLoaiVX = "VX002",
                            NgayHetHan = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgaySanXuat = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoLo = 1
                        },
                        new
                        {
                            MaLieuVX = "VX003-001",
                            MaLoaiVX = "VX003",
                            NgayHetHan = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgaySanXuat = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoLo = 1
                        });
                });

            modelBuilder.Entity("EF_Core.Model.LOAIVACXIN", b =>
                {
                    b.Property<string>("MaLoaiVX")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NuocSX")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoNgayTiemNhac")
                        .HasColumnType("int");

                    b.Property<string>("TenLoaiVX")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaLoaiVX");

                    b.ToTable("LOAIVACXINs");

                    b.HasData(
                        new
                        {
                            MaLoaiVX = "VX001",
                            NuocSX = "Anh",
                            SoNgayTiemNhac = 84,
                            TenLoaiVX = "AstraZeneca"
                        },
                        new
                        {
                            MaLoaiVX = "VX002",
                            NuocSX = "Mỹ",
                            SoNgayTiemNhac = 21,
                            TenLoaiVX = "Pfizer"
                        },
                        new
                        {
                            MaLoaiVX = "VX003",
                            NuocSX = "Nga",
                            SoNgayTiemNhac = 21,
                            TenLoaiVX = "Sputnik V"
                        });
                });

            modelBuilder.Entity("EF_Core.Model.TIEMCHUNG", b =>
                {
                    b.Property<string>("MaTC")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaCD")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaLieuVX")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NgayDkTiemMui2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayTiemMui1")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTiemMui2")
                        .HasColumnType("datetime2");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("MaTC");

                    b.HasIndex("MaCD");

                    b.HasIndex("MaLieuVX");

                    b.ToTable("TIEMCHUNGs");
                });

            modelBuilder.Entity("EF_Core.Model.LIEUVACXIN", b =>
                {
                    b.HasOne("EF_Core.Model.LOAIVACXIN", "LOAIVACXIN")
                        .WithMany("LIEUVACXINs")
                        .HasForeignKey("MaLoaiVX")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LOAIVACXIN");
                });

            modelBuilder.Entity("EF_Core.Model.TIEMCHUNG", b =>
                {
                    b.HasOne("EF_Core.Model.CONGDAN", "CONGDAN")
                        .WithMany("TIEMCHUNGs")
                        .HasForeignKey("MaCD")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EF_Core.Model.LIEUVACXIN", "LIEUVACXIN")
                        .WithMany()
                        .HasForeignKey("MaLieuVX")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CONGDAN");

                    b.Navigation("LIEUVACXIN");
                });

            modelBuilder.Entity("EF_Core.Model.CONGDAN", b =>
                {
                    b.Navigation("TIEMCHUNGs");
                });

            modelBuilder.Entity("EF_Core.Model.LOAIVACXIN", b =>
                {
                    b.Navigation("LIEUVACXINs");
                });
#pragma warning restore 612, 618
        }
    }
}
